### ISSUE TITLE
大佬，FC了

### ISSUE THREAD

**Issue by nodis** [greyovo/CLIP-android-demo#4]
环境：
小米13ultra
安卓13
MIUI 14 V14.0.23.9.18.DEV
开发版
每次都闪退，发生在初始化索引相册时
![Uploading Screenshot_2023-10-08-15-42-22-413_com.miui.home.jpg…]()

java.io.FileNotFoundException: Failed to create image decoder with message 'invalid input'Input contained an error.
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2029)
	at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1934)
	at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:4159)
	at android.content.ContentResolver$$ExternalSyntheticLambda1.call(Unknown Source:10)
	at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1870)
	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1863)
	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:4158)
	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:4142)
	at me.grey.picquery.domain.ImageSearcher.encodePhotoList(ImageSearcher.kt:116)
	at me.grey.picquery.domain.ImageSearcher$encodePhotoList$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at me.grey.picquery.domain.AlbumManager$encodeAlbums$2.invokeSuspend(AlbumManager.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e39da66, androidx.compose.runtime.BroadcastFrameClock@1141a7, StandaloneCoroutine{Cancelling}@7840654, AndroidUiDispatcher@61c79fd]

**Comment by Alpha-chen** [comment]
兄弟 怎么下载clip-image-encoder-quant-int8
clip-text-encoder-quant-int8 这两个模型呢？
